M48
; DRILL file {KiCad 9.0.1} date 2025-04-15T14:17:50+1200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-04-15T14:17:50+12:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.000
%
G90
G05
T1
X60.332Y-33.462
X60.332Y-39.242
T2
X53.6Y-24.5
X60.4Y-24.5
M30
